name: Run Postman Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          newman run https://api.getpostman.com/collections/${{ vars.POSTMAN_COLLECTION_ID }}?apikey=${{ secrets.POSTMAN_API_KEY }} \
          --reporters cli,htmlextra,junit \
          --reporter-htmlextra-export index.html \
          --reporter-junit-export report.xml

      - name: List generated files
        run: |
          ls -l
          cat index.html  # Display the content of index.html to verify

      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    # These permissions are required to generate reports.
    permissions:
      contents: write # To push a branch (gh_pages).

    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Report Artifacts
        uses: actions/download-artifact@v3
        with:
          name: newman-report

      - name: Check if index.html exists
        run: |
          if [ -f "index.html" ]; then
            echo "index.html found!"
          else
            echo "index.html not found!"
            exit 1
          fi

      - name: Create public directory and move HTML report
        run: |
          mkdir -p public  # Create the 'public' folder if it doesn't exist
          mv index.html public/  # Move the HTML report to the 'public' directory

      - name: List files in the public folder
        run: |
          echo "Files in the public folder:"
          ls -l public  # List the contents of the 'public' folder

      - name: Display contents of the index.html file
        run: |
          echo "Contents of the public folder:"
          cat public/index.html  # Display the content of the copied file

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
